# Generated by Django 5.2.11 on 2026-02-15 02:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_km', models.FloatField(default=5.0)),
                ('business_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'searched_areas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_tag_embedding', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('google_types', models.JSONField(blank=True, help_text='Google Places type array, e.g. ["restaurant","food","point_of_interest"]', null=True)),
                ('price_level', models.IntegerField(blank=True, help_text='Google price level: 0=Free, 1=Inexpensive, 2=Moderate, 3=Expensive, 4=Very Expensive', null=True)),
                ('photo_references', models.JSONField(blank=True, help_text='Google Places photo resource names for later retrieval', null=True)),
                ('business_status', models.CharField(blank=True, help_text='Google Places business status, e.g. OPERATIONAL, CLOSED_TEMPORARILY', max_length=30, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('onboarding_status', models.CharField(choices=[('discovered', 'Discovered'), ('contacted', 'Contacted'), ('active', 'Active')], default='discovered', max_length=20)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('user_rating_count', models.IntegerField(default=0, help_text='Total number of Google ratings (from Google Places)')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='api.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='businesses', to='api.tag')),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'db_table': 'businesses',
                'indexes': [models.Index(fields=['avg_rating'], name='idx_business_rating'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_business_embedding', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
