# Generated by Django 5.2.11 on 2026-02-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "automation_logs",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bookmarks",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("lat", models.DecimalField(decimal_places=8, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("contacted", "Contacted"),
                            ("active", "Active"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "businesses",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("icon_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "ai_fraud_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_val",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dividend", "Dividend"),
                            ("standard_coupon", "Standard Coupon"),
                            ("quest_reward", "Quest Reward"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rewards",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("merchant", "Merchant"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("is_verified_human", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("redeemed", "Redeemed"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_coupons",
            },
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.business"
            ),
        ),
        migrations.AddField(
            model_name="automationlog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="provider_business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_rewards",
                to="api.business",
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="trigger_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_rewards",
                to="api.business",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.user",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("high_contrast", models.BooleanField(default=False)),
                ("keyboard_only_nav", models.BooleanField(default=False)),
                ("persona_vector", models.JSONField(blank=True, null=True)),
                ("loyalty_points", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.reward"
            ),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.user",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["ai_fraud_score"], name="idx_review_fraud"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_between_1_5",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["avg_rating"], name="idx_business_rating"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["lat", "lng"], name="idx_business_geo"),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "business")},
        ),
    ]
