# Generated by Django 5.2.11 on 2026-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accessibility',
            field=models.JSONField(blank=True, help_text='Wheelchair accessible entrance/parking/seating/restroom', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='allows_dogs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='dine_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='good_for_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='good_for_groups',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='google_maps_uri',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='live_music',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_hours',
            field=models.JSONField(blank=True, help_text='Google Places opening hours object (periods + weekday text)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='outdoor_seating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='parking',
            field=models.JSONField(blank=True, help_text='Parking options (free, paid, street, garage, valet)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_options',
            field=models.JSONField(blank=True, help_text='Accepted payment methods (credit cards, debit, NFC, cash)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='reservable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='restroom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='reviews_data',
            field=models.JSONField(blank=True, help_text='Google Places reviews array (up to 5 reviews)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_beer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_breakfast',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_brunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_dinner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_lunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='serves_wine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='takeout',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
