# Generated by Django 5.2.11 on 2026-02-18 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rating from Google Places API (stored once during import, never auto-changed)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Display rating: Bayesian estimate when user reviews exist, else google_rating', max_digits=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Number of user reviews on our platform'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('useful', 'Useful'), ('funny', 'Funny'), ('cool', 'Cool')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_votes',
                'constraints': [models.UniqueConstraint(fields=('user', 'review', 'vote_type'), name='unique_vote_per_user_per_review_per_type')],
            },
        ),
    ]
