<!--
  AiSummary.vue — Orbit Scout Summary Banner
  ─────────────────────────────────────────────────────────────────────────────
  Displays a one-line AI-generated summary at the top of search results.
  Shows the Orbit logo + "Orbit Scout:" label + the summary text.

  PROPS
  • text    — the summary string (generated by useAiSummary composable)
  • visible — controls fade transition; hidden when no results yet

  MODULAR FLOW
    useAiSummary() builds the text → SearchPage passes it here as a prop
    → this component purely renders it with a fade-in transition.
  ─────────────────────────────────────────────────────────────────────────────
-->
<template>
  <transition name="summary-fade">
    <div v-if="text && visible" class="ai-summary">
      <img class="ai-summary-logo" src="@/components/icons/orbit-logo.png" alt="Orbit" />
      <div class="ai-summary-body">
        <span class="ai-summary-label">Orbit Scout:</span>
        <span class="ai-summary-text">{{ text }}</span>
      </div>
    </div>
  </transition>
</template>

<script setup>
defineProps({
  text:    { type: String,  default: '' },
  visible: { type: Boolean, default: true },
})
</script>

<style scoped>
.ai-summary {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 0;
  margin-bottom: 18px;
}
.ai-summary-logo {
  flex-shrink: 0;
  width: 52px;
  height: 52px;
  object-fit: contain;
}
.ai-summary-body {
  flex: 1;
  min-width: 0;
  font-size: 14px;
  line-height: 1.55;
  color: var(--color-text, #1e293b);
}
.ai-summary-label {
  font-weight: 700;
  color: var(--color-text, #1e293b);
  margin-right: 4px;
}
.ai-summary-text {
  color: var(--color-text-light, #475569);
}

/* Transition */
.summary-fade-enter-active { transition: opacity 0.4s ease, transform 0.4s ease; }
.summary-fade-leave-active { transition: opacity 0.2s ease; }
.summary-fade-enter-from   { opacity: 0; transform: translateY(-6px); }
.summary-fade-leave-to     { opacity: 0; }
</style>
